### ISSUE TITLE
Foolproof booleans

### ISSUE THREAD

**Issue by lud** [fireproofsocks/dotenvy#16]
Hi, 

Could you be interested in a pull request adding a new type of transform called `:strict_boolean` or `:flag` where it would act like `:boolean` but raise if the value is anything but `"true"`, `"false"`, `"0"` or `"1"`.

This would allow us not to write this:

    stuff_enabled? = env!("MY_VAR", :string!, "false") == "true"
    
Because as it is now, the boolean type is very permissive and people might put stuff like yes/no, on/off, or make mistakes like "flase".

* anything not in `~w(0 1 false true)` would raise with `:flag!` and `:flag`, except...
* ... that an empty string would be considered `false` with `:flag`
* and an empty string would be `nil` with `:flag?` as it is that suffix purpose.

**Comment by fireproofsocks** [comment]
Hmm... I'd have to think about that because one person's idea of "strict" may not match someone else's.

As a workaround that would be visually explicit and upgrade-safe, you could define your own function and apply it, e.g.

```
# runtime.exs
import Config
import Dotenvy

strict_boolean! = fn
  "true" ->
    true

  "1" ->
    true

  "false" ->
    false

  "0" ->
    false

  _ ->
    raise("Variable not strict boolean")
end

config :myapp, :some_bool, env!("SOME_BOOL", strict_boolean!)
```

**Comment by lud** [comment]
> one person's idea of "strict" may not match someone else's

Yes. The `:flag` name seems better to me because you know that you cannot just assume what it is and have to look it up.

A function could be nice indeed, but it should receive the var name as a second argument to raise a proper error message.

It could be done easily without adding the variable name to all `to!` clauses with something like that:

```elixir
def env!(variable, type) when is_function(type, 2) do
    env!(variable, fn value -> type.(value, variable) end)
end
```

**Comment by fireproofsocks** [comment]
Since the detailed error reporting about which variable failed is handled via the `rescue` blocks in `env!/2` and `env!/3`, you could _almost_ do something like this:

```
strict_boolean! = fn
  "true" ->
    true

  "1" ->
    true

  "false" ->
    false

  "0" ->
    false

  _ ->
    raise Dotenvy.Transformer.Error, message: "Values must be one of 0,1,true, or false"
end
```

But the current code fails when it tries to print out the function reference: 
`** (Protocol.UndefinedError) protocol String.Chars not implemented for #Function<42.3316493/1`

I think I should fix the above for sure -- and maybe rename the exception to simply `Dotenvy.Error` for simplicity. That would help keep the core flexible for any other custom modifications (regardless of whether `:flag` or `:strict_boolean` are explicitly supported). 

I tried a quick hack by changing the `rescue` block to something like:
```
  rescue
    error in Error ->
      if is_function(type) do
        reraise "Error converting variable #{variable} using custom function: #{error.message}", __STACKTRACE__
      else
        reraise "Error converting variable #{variable} to #{type}: #{error.message}", __STACKTRACE__
      end
```

and that causes the error message to be reported like this:

```
** (RuntimeError) Error converting variable SOME_BOOL using custom function: Values must be one of 0,1,true, or false
```

Which is decent I think. 

I have to think a bit about opening up the arity of the callback function -- it feels possibly smelly to open up an additional argument just to pass it down to the logs. 🤔  This is why `Logger.metadata/1` is so brilliant, for example: you can add extra info without disrupting any existing calls. 

I think I would prefer to add an attribute to the exception struct -- maybe `:type` or `:name` and then add that to the error message, e.g.

```
reraise "Error converting variable #{variable} using custom function of type #{error.type}:  #{error.message}", __STACKTRACE__
```
and then your custom function could set the value when the error was raised:
```
raise Dotenvy.Transformer.Error,
      message: "Values must be one of 0,1,true, or false",
      type: "strict_boolean"
```

I think that fundamentally accomplishes the visibility (which I agree is important).  What do you think?

**Comment by fireproofsocks** [comment]
Take a look at PR #17 -- it's the candidate for v0.8.0.

**Comment by fireproofsocks** [comment]
I merged and tagged version `0.8.0`.  You can check the docs, but the TL;DR is that custom transform functions can now  `raise Dotenvy.Error` -- I stuck to just the standard `message` attribute since support for additional attributes isn't as straight-forward as I would like and because it's not strictly necessary -- you can do `raise Dotenvy.Error, message: "my_fun expects x, y, z"`

0.8.0 feels like progress, and I want to thank you for bringing these ideas up.  Now `dotenvy` can better support these types of custom functions.  The question is whether this support is sufficient, or if additional transformation types should be introduced.  Are there examples of similar parsers/libraries that define standard values for a flag?  Or define a list of allowed values for a boolean?  I know I'm asking a lot of questions here, but I think that sometimes less is more when it comes to packages.

**Comment by lud** [comment]
Sorry for the delay!

This seems a nice solution.

Thank you :)

>  Are there examples of similar parsers/libraries that define standard values for a flag? Or define a list of allowed values for a boolean? I know I'm asking a lot of questions here, but I think that sometimes less is more when it comes to packages

There is the example of PHP ini config that will accept "true" , "1", "on", "yes", YAML that accepts "no" for false which causes a lot of problems. It's true that everyone will have their own take on this, and custom functions are a nice solution.

**Comment by fireproofsocks** [comment]
Great!  I'll close this but I'm open to adding something to the core later if the custom-function option is too much friction.

Here's the ref for PHP .ini files:

```
; Boolean values can be set to either:
;    true, on, yes
; or false, off, no, none
register_globals = off
track_errors = yes
```

It looks like YAML has gone back and forth on this (?): https://yaml.org/spec/1.2.2/
