### ISSUE TITLE
Feature request: Allow opt-out of `System.fetch_env/1` when variable not found

### ISSUE THREAD

**Issue by arcanemachine** [fireproofsocks/dotenvy#21]
Hello. I ran into an issue which took me a while to debug. Note that I am not using the system environment variables anywhere in my code. Just dotenv files.
 
I have this line in my `config/runtime.exs`:

`postgres_port = env!("POSTGRES_PORT", :integer, 5432)`

None of my dotenv files define a default value for this, so the default should be used. Particularly since I'm not using the system environment variables (as previously mentioned).

The problem arises when we get to my containerized CI environment.

So I'm using GitLab CI, and there are a couple of "services" (other containers) involved in my CI tests. One of them is Postgres.

So when I run the tests in CI, I get this error:

```
** (RuntimeError) Error converting variable POSTGRES_PORT to integer: Unparsable
    (dotenvy 0.8.0) lib/dotenvy/transformer.ex:182: Dotenvy.Transformer.to!/2
    (dotenvy 0.8.0) lib/dotenvy.ex:111: Dotenvy.env!/3
    /builds/user/my_app/config/runtime.exs:23: (file)
    (stdlib 5.2.3) erl_eval.erl:750: :erl_eval.do_apply/7
    (stdlib 5.2.3) erl_eval.erl:1026: :erl_eval.expr_list/7
    (stdlib 5.2.3) erl_eval.erl:292: :erl_eval.expr/6
    (stdlib 5.2.3) erl_eval.erl:282: :erl_eval.expr/6
```

Which is strange, because I haven't defined the value in any of my dotenv files. So it should be falling back to the default value I showed in my first code snippet at the top of this Issue (i.e. `5432`).

The problem is that somewhere in my CI environment, the `POSTGRES_PORT` system environment variable is being declared. On top of that, the container defines `POSTGRES_PORT` as `tcp://172.17.0.3:5432`. This value will (unsurprisingly) not cast to integer, leading to the "Unparsable" error seen above.

In `lib/dotenvy.ex`, there is this code which automatically falls back to using the system environment:

```
  defp fetch_var(variable) do
    :dotenvy_vars
    |> Process.get(%{})
    |> Map.fetch(variable)
    |> case do
      {:ok, value} -> {:ok, value}
      :error -> System.fetch_env(variable)
    end
  end
```

But this creates a very confusing scenario (as I have discovered) since somewhere, the system environment variable may be defined with a given value, for reasons mostly beyond my control.

If my understanding is correct, and there is no means to avoid this issue (I was not able to find one), then perhaps there could be an Application config value to override this feature (or bug, in my situation)? It could even be opt-in for backwards compatibility. For example:

> EDIT: Having dug into this situation a bit, I realize that my proposed solution is not good as it is considered to be [an anti-pattern](https://hexdocs.pm/elixir/design-anti-patterns.html#using-application-configuration-for-libraries). I'm looking into other ways to solve the problem without too much overhead. (EDIT 2: Created #22)

```
  defp fetch_var(variable) do
    fall_back_to_system_env? = Application.get_env(:dotenvy, :fall_back_to_system_env, true)

    :dotenvy_vars
    |> Process.get(%{})
    |> Map.fetch(variable)
    |> case do
      {:ok, value} -> {:ok, value}
      :error -> if fall_back_to_system_env?, do: System.fetch_env(variable), else: :error
    end
  end
```

Perhaps developers could also pick-and-choose which variables they want to override with system environment variables. There could be (as options for this value) the following potential options: `true`, `false`, `{:only, ["VAR_A", "VAR_B"]}`, `{:exclude, ["POSTGRES_HOST", "VAR_B"]}`.

Please let me know your thoughts. I'm willing to put together a proof-of-concept (when I get the time) and make a pull request if you want.

Thanks for making this excellent library.

**Comment by lud** [comment]
I think this should be simpler:

We could just define the function like this:

```elixir
  defp fetch_var(variable) do
    :dotenvy_vars
    |> Process.get(%{})
    |> Map.fetch(variable)
  end
```

Since the system env should be pulled when calling `source!/1` :

```elixir
source!([".env", ".env.#{config_env()}", System.get_env()])
```

There is no need to fallback to `System.fetch_env/2` anywhere at all.

But on the other hand, this library purpose is to make it easier to work with environment variables. Opting out of environment variables is kind of counter productive.

If you app depends on `POSTGRES_PORT` and that variable is defined to an invalid value, you really should fix your CI pipeline. What is the value of the variable?

edit: ah, `tcp://172.17.0.3:5432`, well, that is invalid. It looks like the easy fix there is to have a valid port in there.

You can overwrite system env like this:

```elixir
source!([".env", ".env.#{config_env()}"], side_effect: &System.put_env/1)
```

This will overwrite system's `POSTGRES_PORT` with what is in your file. Or you can just call `System.delete_env("POSTGRES_PORT")` before calling `source!(...)`.

But i'd start by fixing the CI env.

**Comment by arcanemachine** [comment]
Thanks for the reply. That value appears to be declared as part of the default configuration when starting a Postgres container in GitLab CI. I did not set any such environment variable there.

The root of the problem isn't that GitLab CI is declaring an environment variable. The problem is that this package is pulling in configuration data from places I did not tell it to.

If I want to use the system environment, that is easy to do so: Just add `System.get_env()` to the the list of sourced entries in the runtime config. However, this wouldn't have helped the situation in this instance, because the GitLab CI container automatically sets the value by default, so I would have been blindsided by this bug either way.

The real problem is that the application is reaching out to retrieve configuration values from somewhere that I did not ask it to, and ultimately from places that I have no control over, with no way to opt out. (And no way to know what is happening without digging into the source code.)

If there is an interest in modifying the current default behavior, then I am okay with that. However, this would possibly be a breaking change, which is why I whipped up my convoluted solution in my pull request.

From my perspective, the entire concept of automatically "falling back" to the system environment shouldn't even happen. If a developer wants to put `System.get_env()` into the list of sourced values, then Dotenvy can pull from there as it was directed to do so. If I want to retrieve specific values from the system environment, I can do that by calling `System.get_env("SOME_KEY")` myself. But I don't see a good reason for it to automagically pull data from somewhere when it was not instructed to do so, _especially_ if there is no way to circumvent this potentially-wacky behavior. (I would have no idea of this behavior if some stray container didn't decide to inject some environment variable for reasons beyond my control... and I can guarantee that this won't be the last time such a scenario occurs).

Thanks

**Comment by lud** [comment]
>  somewhere that I did not ask it to

> (I would have no idea of this behavior if some stray container didn't decide to inject some environment variable for reasons beyond my control... and I can guarantee that this won't be the last time such a scenario occurs).

> But I don't see a good reason for it to automagically pull data from somewhere when it was not instructed to do so,

I am not sure I follow you. This library main purpose is to fetch environment variables, and validate them.
It allows using files as a convenience for different machines and setups, as fallback.

The fact that you can provide `System.get_env()` in the `source!` is because you can order priority of files.

If you want to only load info from files and _never_ from the environment, why don't you just load values from a JSON file or something? Or just [define your port in the CI](https://docs.gitlab.com/ee/ci/yaml/#variables).

Now I understand your frustration and I guess it would be acceptable to implement your change, but I don't really like the global configuration flag for a library, it's also an anti pattern.

You could define the check like this:

```elixir
fall_back_to_system_env? = Process.get(:dotenvy_vars, :not_sourced) == :not_sourced
```

This way, when the current process has been using `source!` it will not fallback. This only works with the default `:side_effect` though, but other side effects can implement that case as needed. The most common side effect is `&System.put_env/1` and it will happily fallback to system env as intended.

(It's not my library anyway, just my two cents!)

**Comment by fireproofsocks** [comment]
Interesting... thank you for taking the time to file this.  I'd prefer to keep all reading of system envs explicit, so I have to remember what I was thinking with this bit of code... give me a bit to refresh my memory.

**Comment by lud** [comment]
What could be nice is insead of having a `:side_effect` option, we could have a `:backend` or `:store` option, which takes a module who implements `fetch_env/1` and `put_env/1`. That option is written in the process dictionary of the current process.

* By default it would be `System`, so when calling `env!` the lib just calls `System.fetch_env(key)` and, depending on the result, validates the values, uses the default, or raises if there is no default.
* When `source!/2` is called, it puts a `Dotenvy.ProcessDictionaryStore` module in the current process, reads from the sources, and calls `Dotenvy.ProcessDictionaryStore.put_env(values)` with the current values. Now when `env!` is called, the lib will call `Dotenvy.ProcessDictionaryStore.fetch_env(key)` because the process is tagged with that store, and again, validates/uses default/raise.
* `source!/2` accepts the `:store` option that can be set to `System` or another custom module. Custom implementations should be scoped to a process but that would allow to read from another file for specific purposes.

**Benefits**

* Supports @arcanemachine needs by not fetching from system env where `source!` is used.
* Simplify the logic as there is no need for a fallback, just a given module that returns a value for a given key. 
* No need for a fallback option somewhere. No global config for fallback.
* More control to the users and opens the lib for extension.
* Using `env!` deep in the code still fetches from system env by default.

**Drawbacks**

* The `env!` function defaults to `System` unless `source!` is called, then `env!` defaults to the pdict store. I guess this is acceptable as long as it is documented on the `source!` function. "Souricng" means choosing another source of truth for the variables.
* `source!` will now _require_ to pass `System.get_env()` in the list of sources if we want to access environment variables. I believe it is already intended to be this way.

I can help with a PR if both of you are interested.

**Comment by fireproofsocks** [comment]
The feature request you outlined above should probably go inside its own issue so it can have visibility/discussion/etc.  I'd have to consider it... with the latest merge (I'll bump the version here in a second), it sorta makes the calls to `env!/3` always pull out of the process dictionary.  I like the simplicity of that -- nothing up our sleeve.  It's up to you to determine what you put in that dictionary by calling `source/2` or `source!/2`. E.g. you can put in system env vars or ad-hoc maps or the output of any other functions.  I think the explicitness of that is valuable... and I think that keeps things open because the `dotenvy` package wouldn't have any opinions about what you choose to load into the process dictionary.  🤔

**Comment by lud** [comment]
Well I can understand that, but now I would not like to use the library to pull and validate an environment variable in code where performance matters. Because now `source!` must always be called, then make a copy of the system env in the process dictionary to finally get one key out of it.

This limits the usefulness of it to `config/` files only, which is admitedly 99% of the use case, so I'd say everything is fine.

**Comment by fireproofsocks** [comment]
You could put in single keys if you want by supplying a map, e.g.

```
source!([%{"SOME_VAR" => System.fetch_env!("SOME_VAR")}, ".env.#{config_env()}"])
```

The `runtime.exs` config only gets read one when the app starts up -- after that everything is inside the application's process dictionary.  So I'm not overly worried about performance -- or were you thinking of something else?
