### ISSUE TITLE
Overwrite is confusing

### ISSUE THREAD

**Issue by lud** [fireproofsocks/dotenvy#9]
Hi,

If I get this right, according to the code the `overwrite?` option only applies to the predefined variables (default is `System.get_env()`).

Which means that given the following code:

```elixir
[".env", ".env.#{config_env()}"]
|> Enum.filter(&File.regular?(&1))
|> source!(overwrite?: false)
```

The system variables will not be overwritten, but `.env.dev` _will_ overwrite `.env`.

So files have to be listed from lower-precedence to higher-precedence Right?

Now if I would like to have a file `.env.overrides` that does overwrite the system environment, would that be the correct way to do it?:

```elixir
vars = source!([".env.overrides"], overwrite?: true) # with optional System.put_env/1 as a side effect if needed

[".env", ".env.#{config_env()}"]
|> Enum.filter(&File.regular?(&1))
|> source!(overwrite?: false, vars: vars)
```

**Comment by fireproofsocks** [comment]
Thanks for filing the issue! I want to reduce the mental friction around the `:overwrite?` option as well.

You are correct: files to be sourced are listed from lower-precedence to higher-precedence.  Conceptually this is the same as `Map.merge/2` where keys in the right-hand map overwrite keys in the left, so the general pattern is `source([".env", ".overrides.env"])`

The `:overwrite?` option describes _only_ how the results of parsed .env file(s) are merged with existing system ENV variables.  The system environment yields a map of vars.  `Dotenvy.source/2` parses one or more files and yields a map of vars.  The `:overwrite?` option answers the question: "Should the values parsed from .env files take precedence over a pre-existing system env?"

For example, given a `.env` file

```
# .env
LOG_LEVEL=warn
```
and running a command like so:
```
LOG_LEVEL=debug mix run app_using_dotenvy
```

- `env!("LOG_LEVEL")` would return `debug` when `:overwrite?` is `false`.
- `env!("LOG_LEVEL")` would return `warn` when `:overwrite?` is `true`.

Conceptually, you can visualize this by imagining that the system ENVs are another "file" being parsed.  When `:overwrite?` is `false`, the system ENVs can be thought of as having the highest precedence, visualized something like:
```
source([".env", ..., SYSTEM_ENVS])
```
When `:overwrite?` is set to `true`, then they system envs have the _lowest_ precedence, conceptually something like:
```
source([SYSTEM_ENVS, ".env", ... ])
```

I think maybe the confusion here could be reduced if the name were changed to something that better communicated what was going on here.  Perhaps the option name should be ":precedence" and accept a value of `:system` or `:files`?  

-----

If you would like to have files whose values DO overwrite the system environment values, this could be accomplished by setting the `:overwrite?` option to `true` AND by using a side-effect function that sets the values, e.g. `System.put_env/1`:

```
[".env", ".env.#{config_env()}"]
|> source!(overwrite?: false, side_effect: &System.put_env/1)
```
However, generally I would avoid setting system env vars from code because it can make things confusing.

**Comment by lud** [comment]
Thanks for the clarification!

> However, generally I would avoid setting system env vars from code because it can make things confusing.

I agree. Although sometimes it is needed. If you look at my second example, I use a dedicated file for that:

```elixir

# First override system and get the updated vars

vars = source!([".env.overrides"], overwrite?: true) # with optional System.put_env/1 as a side effect if needed


# Then parse regular .env files, giving the new vars as the base, and overwrite? is false

[".env", ".env.#{config_env()}"]
|> Enum.filter(&File.regular?(&1))
|> source!(overwrite?: false, vars: vars)
```

Now, from your pseudocode `source([".env", ..., SYSTEM_ENVS])`, I guess that the following would be a neat way to do it:

```elixir
source([
  ".env",
  ".env.#{config_env()}",
  :system_env,
  ".env.overrides"
])
```

`source/2` would append `:system_env` if not already in here.

Welle that's just me thinking :D

**Comment by fireproofsocks** [comment]
It looks like what you're trying to do is allow for conditional overrides of system env vars (limited to specific vars whitelisted in a dedicated file `.env.overrides`).   Is that correct? I'm not sure why the filtering with `File.regular?/1` is necessary as supplied files are optional and will be skipped if not present unless the `:require_files` option is set.

Without an implementation of the pseudo-code above, then your use of multiple alls to `source/2` makes sense.  Another way to accomplish this might be to enforce the white-listing logic in the `:side_effect` function.

Anyhow, the more I look at it, I really like the idea of declaratively accepting the system envs as an explicit argument to `source/2` -- that way you could place them where-ever you wish.  Perhaps something like so:

```
source!([".env", ".#{config_env()}.env", System.get_env()])
```

That would eliminate the need for the confusing `:overwrite?` option as well as the `:vars` option.  The downside would be that you would *have* to remember to include `System.get_env()` as an argument, but I think it's a sensible improvement for the next version because it is declarative and requires less explanation and it would open the door to working with any other configuration source (e.g. reading from a secure parameter store). 

Any thoughts on this are welcome!

**Comment by lud** [comment]
> Is that correct?

Absolutely. Sometimes you want to use an environment variable that is not only used in the app, like `HOME`. In that case, it is useful to override that when coding.

> I really like the idea of declaratively accepting the system envs as an explicit argument
>
> The downside would be that you would have to remember to include System.get_env()

Right, because if you forget then is it like the default for `overwrite?` was `true`.  `env!/3` will fallback to `System.fetch_env/1` but will use the process dictionary beforehand, if I am correct.

>  open the door to working with any other configuration source (e.g. reading from a secure parameter store)

I worked on this on a tool of mine, based on Dotenvy. The tool uses different env, some listed as "file" and some listed as "dist", and looks for keys defined in dist that are not in "file". I used a [protocol](https://github.com/lud/distopy/blob/main/lib/distopy/source.ex) for that, and you could to the same. If it's a binary, it's a file; if it's a map, it's a raw map of env vars, and otherwise the protocol can be implemented by anyone. Plus it would be a really simple protocol with just `get_vars!/1`.


Another way to look at it is to have `source/2` never overwrite, and provide a second `overwrite/2` function to explicitly pass a second set of sources.

**Comment by fireproofsocks** [comment]
Interesting thoughts.  Yeah, you wouldn't necessarily NEED to include `System.get_env()` in the arguments to `source/2` because as you've noted, `env!/3` will fall back to `System.fetch_env/1`.  Variable substitution is maybe the more important place where you'd need to include `System.get_env()`, e.g. 

```
# sample .env
CACHE_DIR=${PWD}/cache
```
With the proposed changes, there would be no `${PWD}` variable in context unless `System.get_env()` had been included in the list of things to be sourced OR if a file declared that as a variable somewhere.

I'm not sure I follow your example use case with overwriting the `HOME` variable.  Why can't that variable be treated as read-only?

**Comment by lud** [comment]
> I'm not sure I follow your example use case with overwriting the HOME variable. Why can't that variable be treated as read-only?
Not sure I follow you either about the _read only_ :smile: 

Imagine you are writing a work app that spans a small elixir server that tracks your time and stuff. This app is configured by a file in `~/.config/myapp.conf`.

Now when you want to develop that app you want to override the `HOME` env var to not mess with your actual configuration. You want to point `HOME` to `test/fixtures/test.config.1.conf` or something. Because `HOME` exists, it is not like any other `MYAPP_VAR_STUFF` that will solely exist in a context of the deployment of the app.

(to be more precise say you want to test that the app will fallback to `~/config...` if no configuration file path is provided when starting the daemon.)

**Comment by fireproofsocks** [comment]
Ok, v0.6.0 is on deck if you want to try it out and provide any feedback. It's available on branch `source-maps` for a few days before I merge and upgrade. See https://github.com/fireproofsocks/dotenvy/pull/11

**Comment by lud** [comment]
I tested it in a project locally, it works great.

Thank you!

**Comment by fireproofsocks** [comment]
Great!  v0.6.0 has been released.
